## CSV or Excel

In [1]:
import pandas as pd
csv_data = pd.read_csv("age_gender.csv")
print("CSV Loaded:")
csv_data.head()

CSV Loaded:

,age,ethnicity,gender,img_name,pixels
0,1,2,0,20161219203650636.jpg.chip.jpg,129 128 128 126 127 130 133 135 139 142 145 14...
1,1,2,0,20161219222752047.jpg.chip.jpg,164 74 111 168 169 171 175 182 184 188 193 199...
2,1,2,0,20161219222832191.jpg.chip.jpg,67 70 71 70 69 67 70 79 90 103 116 132 145 155...
3,1,2,0,20161220144911423.jpg.chip.jpg,193 197 198 200 199 200 202 203 204 205 208 21...
4,1,2,0,20161220144914327.jpg.chip.jpg,202 205 209 210 209 209 210 211 212 214 218 21...

## Web Scraping Example

In [2]:
!pip install requests beautifulsoup4 pandas --quiet

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://quotes.toscrape.com/page/1/"
html = requests.get(url, headers={"User-Agent": "simple-scraper/1.0"}).text
soup = BeautifulSoup(html, "html.parser")

data = []
for q in soup.select("div.quote"):
    text = q.select_one("span.text").get_text(strip=True)
    author = q.select_one("small.author").get_text(strip=True)
    tags = ",".join([t.get_text(strip=True) for t in q.select(".tags .tag")])
    data.append({"text": text, "author": author, "tags": tags})

df = pd.DataFrame(data)
df

,text,author,tags
0,“The world as we have created it is a process ...,Albert Einstein,"change,deep-thoughts,thinking,world"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities,choices"
2,“There are only two ways to live your life. On...,Albert Einstein,"inspirational,life,live,miracle,miracles"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy,books,classic,humor"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself,inspirational"
5,“Try not to become a man of success. Rather be...,Albert Einstein,"adulthood,success,value"
6,“It is better to be hated for what you are tha...,André Gide,"life,love"
7,"“I have not failed. I've just found 10,000 way...",Thomas A. Edison,"edison,failure,inspirational,paraphrased"
8,“A woman is like a tea bag; you never know how...,Eleanor Roosevelt,misattributed-eleanor-roosevelt
9,"“A day without sunshine is like, you know, nig...",Steve Martin,"humor,obvious,simile"

## Image Collection

In [1]:
!pip install opencv-python pandas --quiet

import cv2
import os
import pandas as pd


folder = r"C:\Users\KIIT0001\Downloads"

image_data = []
image_names = []

for file in os.listdir(folder):
    if file.lower().endswith((".png", ".jpg", ".jpeg")):
        path = os.path.join(folder, file)
        img = cv2.imread(path)
        if img is not None:
            image_data.append(img)
            image_names.append(file)

print("Images loaded:", len(image_data))

pd.DataFrame({
    "filename": image_names,
    "shape (H,W,C)": [img.shape for img in image_data]
})

Images loaded: 39

                                             filename    shape (H,W,C)
0                                        1347446.jpeg  (1528, 3508, 3)
1                                        1351341.jpeg  (2757, 6236, 3)
2   494573354_3896465933833073_181158520520595139_...    (480, 480, 3)
3            4b80c7c7-6dc9-44de-8000-9c9cce3b8fbe.jpg   (736, 1309, 3)
4   61-610649_i-originally-wasnt-going-to-do-any-m...    (421, 840, 3)
5            9961757b-c635-4b44-baab-f9b75511d07f.jpg   (735, 1308, 3)
6                a18fdd33c4846df7be202e0b6d29627f.jpg    (676, 736, 3)
7            ad8da663-5adf-4428-82c1-7a9a9270e855.jpg   (736, 1310, 3)
8                              Anime 4K Wallpaper.jpg   (736, 1656, 3)
9                   chatbot-user-interface-design.png  (1300, 2400, 3)
10        Doctor_Management_Collaboration_Diagram.png    (407, 725, 3)
11                                   download (1).jpg    (403, 463, 3)
12                                       download.jpg   (736, 1308, 3)
13           e0b8ec23-237a-41e6-8bf6-993d4784b2c9.jpg   (736, 1308, 3)
14               e10138041e8a5d17269b8d2fbbfe9736.jpg    (752, 735, 3)
15                                Esh-uTvUcAc-sXC.jpg  (1536, 2048, 3)
16                                EsiM12KVoAEhAsI.png    (523, 443, 3)
17                                EsiNRuRU0AEH32u.jpg   (669, 1194, 3)
18        f418b931-ede6-49bc-abed-b121b735eb85(1).jpg   (736, 1308, 3)
19           f418b931-ede6-49bc-abed-b121b735eb85.jpg   (736, 1308, 3)
20        Hospital_Token_Booking_Sequence_Diagram.png   (447, 1156, 3)
21                                     images (1).jpg    (176, 286, 3)
22                                     images (2).jpg    (226, 223, 3)
23                                         images.jpg    (226, 223, 3)
24                                         images.png    (165, 305, 3)
25                                       IMG_1057.png  (2532, 1170, 3)
26                                       IMG_2280.png  (2532, 1170, 3)
27                                       IMG_2281.png  (2532, 1170, 3)
28                                       IMG_2282.png  (2532, 1170, 3)
29                                       IMG_2287.png  (2532, 1170, 3)
30                                       IMG_4036.jpg  (4032, 3024, 3)
31                                       IMG_4497.jpg  (4032, 3024, 3)
32                                          kiit.jpeg  (1448, 2050, 3)
33                                  KIIT_logo.svg.png   (912, 1200, 3)
34  Venom v4 035 (#200) (2021) (Digital) (Zone-Emp...  (2767, 1800, 3)
35  WhatsApp Image 2025-08-21 at 23.30.31_4a4119ee...  (1268, 1066, 3)
36  WhatsApp Image 2025-10-22 at 20.25.51_90d83642...    (428, 413, 3)
37  WhatsApp Image 2025-10-23 at 13.17.08_5e8c6bdd...   (574, 1280, 3)
38  WhatsApp Image 2025-10-23 at 13.20.02_a0050875...   (574, 1280, 3)

## Extracting from Text files

In [2]:
import os
import pandas as pd


folder = r"C:\Users\KIIT0001\Downloads"

text_data = []
file_names = []

for file in os.listdir(folder):
    if file.lower().endswith(".txt"):
        path = os.path.join(folder, file)
        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                text = f.read()
                text_data.append(text)
                file_names.append(file)
        except Exception as e:
            print(f"Error reading {file}:", e)

print("Text files loaded:", len(text_data))

# Display data as a table
pd.DataFrame({
    "filename": file_names,
    "content": text_data
})

Text files loaded: 2

                    filename                                content
0  New Text Document (2).txt  if u read this, u gonna have leukemia
1      New Text Document.txt                              hello unc