## Comparative study of all the regression methods

the algorithms used : 
1. Linear regression
2. Ridge regression
3. Lasso regression
4. KNN regressor
5. SVR
6. Decision tree regressor
7. Random forest regressor

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score

In [3]:
df = pd.read_csv("bmw.csv")
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0

In [4]:
X = df.drop("price", axis=1)
y = df["price"]

In [5]:
categorical_cols = X.select_dtypes(include=["object"]).columns
numerical_cols = X.select_dtypes(exclude=["object"]).columns

In [6]:
preprocessor_sparse = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", "passthrough", numerical_cols)
    ]
)

In [8]:
preprocessor_dense = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_cols),
        ("num", "passthrough", numerical_cols)
    ]
)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [15]:
models = {
    "Linear Regression": Pipeline([
        ("preprocessor", preprocessor_sparse),
        ("scaler", StandardScaler(with_mean=False)),
        ("model", LinearRegression())
    ]),

    "Ridge Regression": Pipeline([
        ("preprocessor", preprocessor_sparse),
        ("scaler", StandardScaler(with_mean=False)),
        ("model", Ridge())
    ]),

   "Lasso Regression": Pipeline([
    ("preprocessor", preprocessor_sparse),
    ("scaler", StandardScaler(with_mean=False)),
    ("model", Lasso(max_iter=10000))
]),

    "KNN Regressor": Pipeline([
        ("preprocessor", preprocessor_sparse),
        ("scaler", StandardScaler(with_mean=False)),
        ("model", KNeighborsRegressor(n_neighbors=5))
    ]),

    "SVR": Pipeline([
        ("preprocessor", preprocessor_sparse),
        ("scaler", StandardScaler(with_mean=False)),
        ("model", SVR())
    ]),

    "Decision Tree": Pipeline([
        ("preprocessor", preprocessor_sparse),
        ("model", DecisionTreeRegressor(random_state=42))
    ]),

    "Random Forest": Pipeline([
        ("preprocessor", preprocessor_sparse),
        ("model", RandomForestRegressor(random_state=42))
    ])
}

In [13]:
results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)

    results.append({
        "Model": name,
        "R2 Score": r2
    })

results_df = pd.DataFrame(results)
results_df

               Model  R2 Score
0  Linear Regression  0.859809
1   Ridge Regression  0.859798
2   Lasso Regression  0.859773
3      KNN Regressor  0.920840
4                SVR -0.059920
5      Decision Tree  0.905195
6      Random Forest  0.942787